# типы команд CONSOLE и PLAYER.У CONSOLE есть плейсхолден %player%, который меняется на ник игрока, который нажал.

blocks:
  0;0;0;spawn: # координаты, делимитер "-"
    command: "menu" # сама команда, которая будет при нажатии
    type: PLAYER
  0;10;0;spawn:
    command: "openmenu %player%"
    type: CONSOLE